In [1]:
import pandas as pd
import numpy as np

1st Question

In [3]:
df =pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

In [4]:
#Create Age Series
age_series = df['Age']

In [5]:
#Descriptive Statistics
print(age_series.describe())

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [6]:
# Create Age Groups
bins = [0, 12, 18, 35, 60, 100]
labels = ['Child', 'Teen', 'Young Adult', 'Adult', 'Senior']

df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels)

In [7]:
# Fatality Rate
fatality = df.groupby('AgeGroup')['Survived'].apply(lambda x: 1 - x.mean())
print(fatality)

AgeGroup
Child          0.420290
Teen           0.571429
Young Adult    0.617318
Adult          0.600000
Senior         0.772727
Name: Survived, dtype: float64

/tmp/ipykernel_675/1905416096.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  fatality = df.groupby('AgeGroup')['Survived'].apply(lambda x: 1 - x.mean())

**Conclusion** : Most passengers were young adults, and this group had the highest fatality rate. This happened mainly because children and women were given priority during rescue, leaving many adult males behind.

2nd Question

In [8]:
#Survival Rate
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [9]:
#Boolean Filtering
survivors = df[df['Survived'] == 1]
dead = df[df['Survived'] == 0]

In [10]:
# Gender Comparison
df.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

**Conclusion** : First-class passengers had the best survival rate because they had better access to lifeboats. Also, females survived more than males, showing that both class and gender played a major role.

3rd Question

In [11]:
#Find Missing Values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
AgeGroup       177
dtype: int64

In [13]:
#Fill with Mean and Median
mean_age = df['Age'].fillna(df['Age'].mean())
median_age = df['Age'].fillna(df['Age'].median())
print(df['Age'].mean(), df['Age'].median())

29.69911764705882 28.0

**Conclusion** : The Age column has missing values, and using the median is better than the mean. This is because median is not affected much by extreme values and gives a more realistic estimate.

4th Question

In [14]:
#Hierarchical Indexing
df_multi = df.set_index(['Pclass', 'Sex'])

In [15]:
# Using loc
df_multi.loc[1]   # Pclass 1

,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
Sex,,,,,,,,,,,
female,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,Adult
female,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,Young Adult
male,7,0,"McCarthy, Mr. Timothy J",54.0,0,0,17463,51.8625,E46,S,Adult
female,12,1,"Bonnell, Miss. Elizabeth",58.0,0,0,113783,26.5500,C103,S,Adult
male,24,1,"Sloper, Mr. William Thompson",28.0,0,0,113788,35.5000,A6,S,Young Adult
...,...,...,...,...,...,...,...,...,...,...,...
female,872,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",47.0,1,1,11751,52.5542,D35,S,Adult
male,873,0,"Carlsson, Mr. Frans Olof",33.0,0,0,695,5.0000,B51 B53 B55,S,Young Adult
female,880,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",56.0,0,1,11767,83.1583,C50,C,Adult
female,888,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,Young Adult
male,890,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,Young Adult

In [16]:
#Using xs()
df_multi.xs('female', level='Sex')

,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
Pclass,,,,,,,,,,,
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,Adult
3,3,1,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Young Adult
1,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,Young Adult
3,9,1,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,0,2,347742,11.1333,NaN,S,Young Adult
2,10,1,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,1,0,237736,30.0708,NaN,C,Teen
...,...,...,...,...,...,...,...,...,...,...,...
2,881,1,"Shelley, Mrs. William (Imanita Parrish Hall)",25.0,0,1,230433,26.0000,NaN,S,Young Adult
3,883,0,"Dahlberg, Miss. Gerda Ulrika",22.0,0,0,7552,10.5167,NaN,S,Young Adult
3,886,0,"Rice, Mrs. William (Margaret Norton)",39.0,0,5,382652,29.1250,NaN,Q,Adult
1,888,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,Young Adult
3,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN

In [17]:
#Survival Count
df_multi.groupby(level=['Pclass','Sex'])['Survived'].sum()

Pclass  Sex
1       female    91
        male      45
2       female    70
        male      17
3       female    72
        male      47
Name: Survived, dtype: int64

**Conclusion** : Hierarchical indexing using Pclass and Sex makes the data more organized. It helps us easily compare survival patterns across different groups without confusion.

5th Question

In [19]:
#Create FamilySize and  SurvivalScore
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['SurvivalScore'] = np.log1p(df['Fare']) * df['FamilySize']

In [20]:
# Sort
df_sorted = df.sort_values(by='SurvivalScore', ascending=False)
df_sorted.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup,FamilySize,SurvivalScore
324,325,0,3,"Sage, Mr. George John Jr",male,NaN,8,2,CA. 2343,69.55,NaN,S,NaN,11,46.819538
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.55,NaN,S,NaN,11,46.819538
792,793,0,3,"Sage, Miss. Stella Anna",female,NaN,8,2,CA. 2343,69.55,NaN,S,NaN,11,46.819538
201,202,0,3,"Sage, Mr. Frederick",male,NaN,8,2,CA. 2343,69.55,NaN,S,NaN,11,46.819538
159,160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,69.55,NaN,S,NaN,11,46.819538

**Conclusion** : By creating FamilySize and combining it with Fare, we get a SurvivalScore that gives a better idea of survival chances. This shows how creating new features can improve analysis.

6th Question

In [21]:
# Index Alignment
fare_avg = df.groupby('Pclass')['Fare'].mean()
age_avg = df.groupby('Pclass')['Age'].mean()

In [22]:
#Arithmetic Operation
result = fare_avg + age_avg
print(result)

Pclass
1    122.388128
2     50.539813
3     38.816170
dtype: float64

**Conclusion** : Pandas automatically aligns data based on index labels like Pclass. So even when combining different Series, the values match correctly without manual adjustment.

7th question

In [23]:
# Embarked vs Survival
df.groupby('Embarked')['Survived'].mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [24]:
# Hierarchical
df.groupby(['Embarked','Pclass'])['Survived'].mean()

Embarked  Pclass
C         1         0.694118
          2         0.529412
          3         0.378788
Q         1         0.500000
          2         0.666667
          3         0.375000
S         1         0.582677
          2         0.463415
          3         0.189802
Name: Survived, dtype: float64

**Conclusion** : The port of embarkation shows some differences in survival rates, but it is not as important as factors like class and gender. Its effect is more indirect.

8th Question

In [26]:
# Function
def categorize(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'
df['AgeCategory'] = df['Age'].apply(categorize)

In [27]:
#pivot
pivot = pd.pivot_table(df, values='Survived',
                       index='AgeCategory',
                       columns='Sex',
                       aggfunc='mean')
print(pivot)

Sex            female      male
AgeCategory
Adult        0.767327  0.179625
Child        0.690909  0.396552
Senior       0.701754  0.130137

**Conclusion** : Dividing passengers into age categories like Child, Adult, and Senior makes the analysis clearer. It shows that children and females had better survival chances.

9th Question

In [28]:
# Check null values
df.isnull().sum()

PassengerId        0
Survived           0
Pclass             0
Name               0
Sex                0
Age              177
SibSp              0
Parch              0
Ticket             0
Fare               0
Cabin            687
Embarked           2
AgeGroup         177
FamilySize         0
SurvivalScore      0
AgeCategory        0
dtype: int64

In [29]:
# drop rows
df_drop = df.dropna(thresh=5)

In [30]:
# Drop columns
df.dropna(axis=1, inplace=True)

**Conclusion** : Different columns have different missing value patterns, so we need a mixed approach. Filling important columns like Age and dropping highly missing ones like Cabin gives better results.

10th Question

In [31]:
#Multi-level Groupby + Reshape
grouped = df.groupby(['Pclass','Sex','Survived']).size()

In [32]:
# Unstack
table = grouped.unstack()
print(table)

Survived         0   1
Pclass Sex
1      female    3  91
       male     77  45
2      female    6  70
       male     91  17
3      female   72  72
       male    300  47

In [33]:
#Stack back
table.stack()

Pclass  Sex     Survived
1       female  0             3
                1            91
        male    0            77
                1            45
2       female  0             6
                1            70
        male    0            91
                1            17
3       female  0            72
                1            72
        male    0           300
                1            47
dtype: int64

**Conclusion** : Using multi-level groupby and reshaping the data helps present survival patterns in a clear way. It makes it easy to compare how class and gender affected survival.